### ISSUE TITLE
Experiência com Github Copilot

### ISSUE THREAD

**Issue by patriciamsg** [microsoft/Mastering-GitHub-Copilot-for-Paired-Programming#105]
Comecei a utilizar a pouco tempo e posso dizer que é uma ferramenta que facilita muito o trabalho no dia a dia.

**Comment by cyz** [comment]
Obrigada por compartilhar - Participe da nossa série GitHub Foundations em Português em Outubro: https://aka.ms/brasil/githubfoundations
