### ISSUE TITLE
Minha experiência utilizando Github copilot

### ISSUE THREAD

**Issue by luluzinhaDev** [microsoft/Mastering-GitHub-Copilot-for-Paired-Programming#106]
Comecei a utilizar a uns 3 meses e facilitou muito meu dia dia, auxiliando principalmente a solucionar erros na aplicação e criar testes unitários para minha aplicação

**Comment by cyz** [comment]
Obrigada por compartilhar - Participe da nossa série GitHub Foundations em Português em Outubro: https://aka.ms/brasil/githubfoundations
