### ISSUE TITLE
Github copillot e minha experiência

### ISSUE THREAD

**Issue by SchulzeEdi** [microsoft/Mastering-GitHub-Copilot-for-Paired-Programming#108]
Github Copilot depois que iniciei a utilização mudou a minha produtividade relacionada ao dia a dia e entregas de sprint. Ajudando toda a empresa da qual atuo, além de projetos pessoais do qual realizo. Eu que trabalho realizando modelos de i.a preditiva e chatbot com i.a generativa, auxilia coisas que seriam mais simples, me preocupando realmente com o que importa.

**Comment by cyz** [comment]
Obrigada por compartilhar - Participe da nossa série GitHub Foundations em Português em Outubro: https://aka.ms/brasil/githubfoundations
