### ISSUE TITLE
Minha experiência com o GitHub Copilot

### ISSUE THREAD

**Issue by nataliamanosso** [microsoft/Mastering-GitHub-Copilot-for-Paired-Programming#111]
Gostei bastante, a IA consegue se adaptar muito com o seu codigo e cada vez dar sugestões melhores, e te incentiva a escrever padroes entendiveis

**Comment by cyz** [comment]
Obrigada por compartilhar - Participe da nossa série GitHub Foundations em Português em Outubro: https://aka.ms/brasil/githubfoundations
