### ISSUE TITLE
Experiência com o github copilot

### ISSUE THREAD

**Issue by wdeoliveirawill** [microsoft/Mastering-GitHub-Copilot-for-Paired-Programming#117]
Utilizo o serviço desde o início e cada vez mais o classifico como uma grande aliada do desenvolvimento. Em momento algum ele substitui o dev, mas naqueles momentos em que você está "travado" e sem uma direção clara ele consegue dar uma sugestão que te traz de novo ao foco do problema que quer resolver. Mas sem dúvida nenhuma o que mais uso é a busca com contexto onde com uma simples seleção do erro já consigo ter uma resposta do que pode estar acontecendo e sugestões de resoluções do erro.

**Comment by cyz** [comment]
Obrigada por compartilhar - Participe da nossa série GitHub Foundations em Português em Outubro: https://aka.ms/brasil/githubfoundations
