### ISSUE TITLE
Minha experiência utilizando github copilot

### ISSUE THREAD

**Issue by zattagabriela** [microsoft/Mastering-GitHub-Copilot-for-Paired-Programming#118]
Recentemente comecei utilizar o github copilot para desenvolvimento de projetos pessoais e profissionais e tem sido uma experiência muito boa, ganhei eficiência na construção de novas soluções e correções de bugs além de agilizar o planejamento de entregas também.

**Comment by cyz** [comment]
Obrigada por compartilhar - Participe da nossa série GitHub Foundations em Português em Outubro: https://aka.ms/brasil/githubfoundations
