### ISSUE TITLE
Crescimento profissional e mudança de área

### ISSUE THREAD

**Issue by santos-arthur** [microsoft/Mastering-GitHub-Copilot-for-Paired-Programming#125]
Durante o último ano, fiz uma mudança na minha carreira, tentando alçar cargos de maior importância e buscando melhorar o meu status profissional. O copilot me ajudou a transportar toda a minha experiência de desenvolvimento em uma linguagem para quase qualquer outra. Atualmente estou no cargo que desejava, reportando diretamente pra um dos gerentes da área de sistemas da empresa, podendo assumir ainda mais responsabilidades e tendo certeza que terei uma agilidade muito alta na produção e na revisão do que for necessário.

**Comment by cyz** [comment]
Obrigada por compartilhar - Participe da nossa série GitHub Foundations em Português em Outubro: https://aka.ms/brasil/githubfoundations
