### ISSUE TITLE
Um bom aliado

### ISSUE THREAD

**Issue by bezalelmiranda** [microsoft/Mastering-GitHub-Copilot-for-Paired-Programming#126]
Além de aumentar a produtividade e sugerir boas práticas no código. Ajuda a sedimentar o conhecimento e a se preocupar em resolver o problema.

**Comment by cyz** [comment]
Obrigada por compartilhar - Participe da nossa série GitHub Foundations em Português em Outubro: https://aka.ms/brasil/githubfoundations
