### ISSUE TITLE
Como o copilot pode te salvar?

### ISSUE THREAD

**Issue by victormilk** [microsoft/Mastering-GitHub-Copilot-for-Paired-Programming#128]
# Como economizar tempo?
Essa é uma pergunta bem fácil, com o uso do copilot consegui reduzir em mais `80%` o tempo utilizado na criação de testes unitários e integração, também tive uma redução na complexidade em resolução de diversos problemas, com essa ferramenta maravilhosa consegui desenvolver meus códigos com maior qualidade e com menor tempo.

# Tem concorrência?
Já experimentei diversas outras alternativas, porém nenhuma conseguiu entregar o que o copilot me proporcionou, então minha conclusão é que não possui concorrência.

**Comment by cyz** [comment]
Obrigada por compartilhar - Participe da nossa série GitHub Foundations em Português em Outubro: https://aka.ms/brasil/githubfoundations
