### ISSUE TITLE
Copilot é essencial

### ISSUE THREAD

**Issue by gianluca-pettenon** [microsoft/Mastering-GitHub-Copilot-for-Paired-Programming#131]
O copilot foi o primeiro contato que tive com uma IA em minha IDE, e desde então, utilizo quase sempre, se não, sempre. O  auto complete acaba enxugando um trabalho grande e ajuda a não perder a ideia do negócio do momento, tornando-se uma ferramenta/amigo do desenvolvedor.

**Comment by cyz** [comment]
Obrigada por compartilhar - Participe da nossa série GitHub Foundations em Português em Outubro: https://aka.ms/brasil/githubfoundations
