### ISSUE TITLE
I miss you, Copilot

### ISSUE THREAD

**Issue by matheustkn** [microsoft/Mastering-GitHub-Copilot-for-Paired-Programming#132]
**Capítulo 1:** O encontro

Assim que anunciaram o copilot fiquei muito empolgado e já me inscrevi para participar dos testes e fui aprovado. Inicialmente parecia algo surreal em que cada coisa que ele me ajudava era como se fosse mágica! Mostrei para todos meus amigos que são devs e eles sempre falavam "compartilha tela e mostra pra fulano isso ai". Com passar do tempo eu já considerava o copilot como meu amigo pessoal, conversávamos o dia todo sobre código, corrigindo e ensinando. Enfim, virei especialista em copilot.

**Capítulo 2:** A separação

Quando acabou o período de avaliação, continuei utilizando o copilot como estudante pois estava concluindo uma graduação em ADS. Mas de 3 meses para cá tentei utilizar algo novo porque achei que não faria tanta diferença, até cheguei comprar o plano Anual mas lembrei que tinha outras prioridades e acabei cancelando a compra horas depois.

**Capítulo 3:** A palestra no evento da Codecon

Quando a Cynthia Zanoni (@cyz) começou a falar sobre o copilot, cada palavra que ela falava era uma lágrima minha que descia. E quando ela falou sobre as novas features e como o copilot se comportava, eu me sentia orgulhoso de saber o quanto ele cresceu. Adorei a palestra, todos os assuntos que foram abordados foram muito bons, bem explicado e incisivos.

Essa não é uma issue, somente um desabafo. 😭

**Comment by cyz** [comment]
Obrigada por compartilhar - Participe da nossa série GitHub Foundations em Português em Outubro: https://aka.ms/brasil/githubfoundations
