### ISSUE TITLE
Minha experiência com o Copilot

### ISSUE THREAD

**Issue by andreiflancanova** [microsoft/Mastering-GitHub-Copilot-for-Paired-Programming#133]
Aprendi muito na palestra da Cynthia, pois saber fazer prompts assertivos é fundamental para poder ganhar produtividade e extrair o melhor que a IA pode oferecer. Uso o Copilot integrado às minhas IDEs do dia-a-dia, VSCode e IntelliJ e está sendo uma baita experiência.

Uma dica que recomendo é saber dar o contexto para o Copilot. Ex.:

``` bash
Considere que você é um desenvolvedor sênior com 5 anos de experiência em desenvolvimento da stack XPTO. Crie ...
```

Muito obrigado pela oportunidade.

A CodeCon Summit 2024 foi o meu primeiro evento de tecnologia, e já estou ansioso pelo próximo!

**Comment by cyz** [comment]
Obrigada por compartilhar - Participe da nossa série GitHub Foundations em Português em Outubro: https://aka.ms/brasil/githubfoundations
