### ISSUE TITLE
Copilot, vale estudar

### ISSUE THREAD

**Issue by uberGadelha** [microsoft/Mastering-GitHub-Copilot-for-Paired-Programming#135]
Eu conhecia o Copilot apenas naquela barra de navegador e sempre achei meio palha, tanto que nem cogitei em utilizar para outros fins, mesmo para pair programming.

Em uma palestra de Github meus olhos foram abertos e notei o poder que essa ferramenta (copilot) tem para ajudar em códigos, me fez querer dar uma segunda chance para o Copilet e testar o potencial dele no meu trabalho e dia a dia.

Até então, tem sido um um excelente suporte para auxiliar em soluções, padrões de códigos e até mesmo para ajudar em dúvidas com regras de negócios complexas.

**Comment by cyz** [comment]
Obrigada por compartilhar - Participe da nossa série GitHub Foundations em Português em Outubro: https://aka.ms/brasil/githubfoundations
