### ISSUE TITLE
github 101 - copilot.pdf is broken

### ISSUE THREAD

**Issue by YYvanYang** [microsoft/Mastering-GitHub-Copilot-for-Paired-Programming#3]
[github 101 - copilot.pdf](https://github.com/microsoft/Mastering-GitHub-Copilot-for-Paired-Programming/blob/main/03-Introduction-to-GitHub-Copilot/github%20101%20-%20copilot.pdf)

**Comment by WirelessLife** [comment]
New presentation uploaded and tested.  Thank you for the heads up.
