### ISSUE TITLE
Feedback sobre o curso "Mastering GitHub Copilot for AI Paired Programming"

### ISSUE THREAD

**Issue by felipealbuquerq** [microsoft/Mastering-GitHub-Copilot-for-Paired-Programming#35]
Olá Cynthia,

Gostaria de compartilhar meu feedback sobre o curso "Mastering GitHub Copilot for AI Paired Programming" que você ministrou na CodeCon. Foi muito interessante ver como você aborda o tema do copiloto e suas implicações para o desenvolvimento de software.

Algumas observações que gostaria de fazer:

1. O conceito de "copiloto" foi muito bem explicado. É verdade que o controle final está sempre conosco, os copilotos nos ajudam a navegar por diferentes caminhos possíveis.

2. Você abriu portas para muitas outras tecnologias além da nossa área específica. Isso é muito valioso para desenvolvedores que querem expandir seus horizontes.

3. Me lembrei de dois projetos pessoais que tenho trabalhado recentemente:
- O Wonex, um projeto pessoal que estou desenvolvendo
- O phind.com, que uso atualmente como um tipo de copiloto

Ambos esses projetos demonstram como podemos aplicar os conceitos aprendidos no curso em cenários práticos.

4. Sua apresentação na CodeCon foi excelente. O overview que você deu foi muito claro e informativo.

5. Gostaria de saber se existem planos para adicionar mais conteúdo sobre integração com outras ferramentas ou plataformas populares, como Jupyter Notebooks ou IDEs específicas?

6. Seria ótimo ter exemplos práticos de como usar o GitHub Copilot em diferentes linguagens de programação, especialmente em linguagens menos comuns.

7. Talvez seja útil incluir um capítulo sobre ética e privacidade ao usar ferramentas de IA como o GitHub Copilot.

Agradeço pela oportunidade de participar desse curso e espero que essas sugestões sejam úteis. Parabéns pelo trabalho excelente!

PS: Morei no Colégio Agrícola de Prudente pra conseguir fazer o Técnico em Informática e meu primeiro controle de estoque foi em Delphi e por isso me identifiquei muito com sua história ❤️

**Comment by cyz** [comment]
Obrigada por compartilhar - Participe da nossa série GitHub Foundations em Português em Outubro: https://aka.ms/brasil/githubfoundations
