### ISSUE TITLE
Uso profissional do copilot

### ISSUE THREAD

**Issue by LeandroLeiteC** [microsoft/Mastering-GitHub-Copilot-for-Paired-Programming#37]
Hoje diariamente no meu trabalho como software developer utilizo o copilot para aumentar minha produtividade. 

Por diversas vezes o copilot já escreveu arquivos com centenas de linhas de testes unitários pra mim! (Mesmo a linguagem do service sendo Clojure que é uma linguagem funcional).

O copilot consegue acompanhar a arquitetura que seguimos na empresa (variante do clean architecture e DDD que chamamos de diplomat). 

Percebi que o copilot funciona melhor ainda com códigos bem organizados, coesos e bem escritos, o código gerado é altamente compatível com o restante do projeto. Hoje não vivo sem, fiz até questão de pagar para ter o melhor do copilot.  Inclusive amo a integração com o plugin do IntelliJ com o chat, peço tradução, geração de funções e regex.

Recomendo muito e mesmo pagando ainda é o melhor custo benefício do mercado.

**Comment by cyz** [comment]
Obrigada por compartilhar - Participe da nossa série GitHub Foundations em Português em Outubro: https://aka.ms/brasil/githubfoundations
