### ISSUE TITLE
Feedback sobre a utilização do Github Copilot

### ISSUE THREAD

**Issue by Felipe-Feyh** [microsoft/Mastering-GitHub-Copilot-for-Paired-Programming#39]
Utilizo o copilot a aproximadamente um ano, integrado ao Intelij e vscode, e realmente vem contribuindo com minhas entregas. Sou desenvolvedor Java Júnior, e o copilot acaba me auxiliando tanto nas sugestões de código, como também agilizando minha curva de aprendizagem, pois sempre surge uma forma alternativa a que eu pensei inicialmente.  

Outro aspecto que gosto é relativo ao auxílio na construção de testes unitários, utilizo bastante para criar meus mocks.

**Comment by cyz** [comment]
Obrigada por compartilhar - Participe da nossa série GitHub Foundations em Português em Outubro: https://aka.ms/brasil/githubfoundations
