### ISSUE TITLE
Experiência com Github copilot

### ISSUE THREAD

**Issue by cnmoro** [microsoft/Mastering-GitHub-Copilot-for-Paired-Programming#40]
Uso o copilot desde o lançamento, e isso trouxe um ganho de produtividade gigante. Apesar de fácil, existe uma curva de aprendizado, é necessário entender a melhor forma de "engatilhar" a melhor sugestão de código, seja com inserção de comentários ou quebrar a lógica em mais etapas bem definidas.

Quando o copilot chat saiu, foi a cereja no bolo, evitando ter que ficar copiando código e jogando fora da IDE no chatgpt.

Ele funciona melhor quando você precisa executar ações repetidas, por exemplo, escrever um json schema ou então definir vários endpoints em sequência do mesmo contexto.

Acho que daqui pra frente, usar esse tipo de  ferramenta vai virar o padrão!

#codecon

**Comment by cyz** [comment]
Obrigada por compartilhar - Participe da nossa série GitHub Foundations em Português em Outubro: https://aka.ms/brasil/githubfoundations
