### ISSUE TITLE
Feedback sobre copilot

### ISSUE THREAD

**Issue by PedroUbine06s** [microsoft/Mastering-GitHub-Copilot-for-Paired-Programming#43]
Olá eu uso o copilot deve fazer +- 5 meses.

Um feedback que eu gostsria fazer é uma crítica as vezes eu sinto que auto complete falha quando eu estou refatorando alguma função.

A maneira que eu refatoro é reescrever q função nova embaixo da original, as vezes eu criou uma função anônima ou if e o copilot para de trazer o autocomplete.

**Comment by cyz** [comment]
Obrigada por compartilhar - Participe da nossa série GitHub Foundations em Português em Outubro: https://aka.ms/brasil/githubfoundations
