### ISSUE TITLE
Feedback Mayara Luiza Gonçalves

### ISSUE THREAD

**Issue by Maylui2** [microsoft/Mastering-GitHub-Copilot-for-Paired-Programming#45]
Olá tudo bem ? Quero deixar meu sincero relato aqui. Essa palestra foi uma inspiração, é muito gratificante ver uma mulher na tecnologia no palco, falando sobre sua história, seu passado, e muito além, trazer novidades e demonstrar elas na palestra como o github copilot, você me tirou várias dúvidas mas a maior delas é que como mulher, consigo chegar onde você chegou, basta ter dedicação e estudos. 
Foi a melhor palestra até agora. 
💗👩🏻‍💻 WOMAN TECH

**Comment by cyz** [comment]
Obrigada por compartilhar - Participe da nossa série GitHub Foundations em Português em Outubro: https://aka.ms/brasil/githubfoundations
