### ISSUE TITLE
Feedback sobre experiência com o Github Copilot

### ISSUE THREAD

**Issue by hernanijr** [microsoft/Mastering-GitHub-Copilot-for-Paired-Programming#46]
Uso o copilot desde quando tinha acesso ao Github Pro pelo acesso educacional da Faculdade, quando ainda estava em beta, após sair da faculdade fiz a minha própria assinatura.

Me auxilia bastante em tarefas repetitivas e mecânicas, quando preciso gerar massas de testes ou dados que seguem algum padrão, ele é muito rápido nisso.

Ou para seguir algum template/boilerplate ele preenche rapidamente o que preciso identificando os arquivos do projeto.

Hoje não fico sem mais, me dá muita produtividade e me faz pensar apenas no que importa para o sistema.

**Comment by cyz** [comment]
Obrigada por compartilhar - Participe da nossa série GitHub Foundations em Português em Outubro: https://aka.ms/brasil/githubfoundations
