### ISSUE TITLE
Experiência com Github Copilot

### ISSUE THREAD

**Issue by LarissaAzevedo** [microsoft/Mastering-GitHub-Copilot-for-Paired-Programming#47]
Ter como escrever terminações de funções mais rapidamente, sugestões de testes para meus componentes no front-end e até refatorações de métodos considerando performance com JS foi excepcional.

É uma ferramenta que não quero me desapegar tão cedo.

**Comment by cyz** [comment]
Obrigada por compartilhar - Participe da nossa série GitHub Foundations em Português em Outubro: https://aka.ms/brasil/githubfoundations
