### ISSUE TITLE
Experiência usando copilot

### ISSUE THREAD

**Issue by daianessousa** [microsoft/Mastering-GitHub-Copilot-for-Paired-Programming#48]
Utilizo o copilot no dia a dia principalmente para duas atividades: 
1. Pedir explicações sobre especificidades de linguagens que não tenho conhecimento. Geralmente me ajuda muito a entender uma linguagem nova e mesmo a aprender mais. 
2. Para auto completar códigos que são repetitivos
3. Para criar documentações de alterações que fiz no código e colocar mais informações na descrição dos PR.

**Comment by cyz** [comment]
Obrigada por compartilhar - Participe da nossa série GitHub Foundations em Português em Outubro: https://aka.ms/brasil/githubfoundations
