### ISSUE TITLE
Experiência utilizando Copilot

### ISSUE THREAD

**Issue by betossauro** [microsoft/Mastering-GitHub-Copilot-for-Paired-Programming#49]
Utilizando o copilot a mais de um ano, desde que adquiri a conta de estudante, me auxiliou em diversos momentos, desde centralização de div quanto a coisas mais complexas me ajudando com o contexto de código e solucionando problemas rápidos. É uma tecnologia que não consigo mais ficar sem.

#codecon

**Comment by cyz** [comment]
Obrigada por compartilhar - Participe da nossa série GitHub Foundations em Português em Outubro: https://aka.ms/brasil/githubfoundations
