### ISSUE TITLE
Uso do Copilot

### ISSUE THREAD

**Issue by devlongen** [microsoft/Mastering-GitHub-Copilot-for-Paired-Programming#50]
Ainda não usufrui muito, porém interface não me agradou muito, poderia ter uma introdução um pouco mais simples e deixar mais chamativo para mais o uso

**Comment by cyz** [comment]
Obrigada por compartilhar - Participe da nossa série GitHub Foundations em Português em Outubro: https://aka.ms/brasil/githubfoundations
