### ISSUE TITLE
Sobre o uso do Copilot

### ISSUE THREAD

**Issue by farchettiensis** [microsoft/Mastering-GitHub-Copilot-for-Paired-Programming#51]
Já tenho alguns meses de experiência usando o GitHub Copilot em diferentes IDEs e virou parte do meu trabalho, desde um assistente que detecta padrões repetitivos e poupa tempo ao escrever boilerplate code, mas também para ajudar a resolver problemas no código e até explicar questões, erros. 

Como ele tem acesso ao código e ao contexto, torna-se um assistente muito eficaz para diversas tarefas. Ferramenta muito importante para o meu dia a dia!

**Comment by cyz** [comment]
Obrigada por compartilhar - Participe da nossa série GitHub Foundations em Português em Outubro: https://aka.ms/brasil/githubfoundations
