### ISSUE TITLE
Experiência utilizando o Copilot

### ISSUE THREAD

**Issue by aliceborges** [microsoft/Mastering-GitHub-Copilot-for-Paired-Programming#53]
Utilizei o Copilot por muito tempo enquanto trabalhei no Mercado Livre, e fez total diferença no dia a dia. Acelerou meu desenvolvimento, as entregas, até porque gerava blocos de código em testes unitários de forma muito rápida e automatizada, se baseando nos cenários já desenvolvidos.
É uma ferramenta extremamente valiosa no dia a dia dos desenvolvedores, e que com certeza faz valer a pena o investimento.
#codecon

**Comment by cyz** [comment]
Obrigada por compartilhar - Participe da nossa série GitHub Foundations em Português em Outubro: https://aka.ms/brasil/githubfoundations
