### ISSUE TITLE
Experiência Git copilot

### ISSUE THREAD

**Issue by leticiasoaresfl** [microsoft/Mastering-GitHub-Copilot-for-Paired-Programming#56]
Usar o Copilot no dia a dia é muito bom, facilita escritas no código que permite diminuição do tempo, porém sempre importante salientar que algumas vezes o autocompletar pode não ser o que você necessita e por isso demanda de atenção.

**Comment by cyz** [comment]
Obrigada por compartilhar - Participe da nossa série GitHub Foundations em Português em Outubro: https://aka.ms/brasil/githubfoundations
