### ISSUE TITLE
Experiencia Github Copilot

### ISSUE THREAD

**Issue by jwcbmat** [microsoft/Mastering-GitHub-Copilot-for-Paired-Programming#58]
Uso Github copilot a 7 meses. Gosto da simplificação que ele tras, resultados diretos dentro do contexto. Alem de hoje em dia ter um chat embutido, consigo adicionar "mini" chats direto em meu codigo para direcionar o contexto.

CodeCon

**Comment by BrunoSHonorio7** [comment]
Como desenvolvedor iniciante, o GitHub Copilot tem sido muito útil na minha jornada de aprendizado. Mostrando diferentes estilos de codificação e me ajuda a entender conceitos mais avançados. É como ter um tutor personalizado que me mostra as melhores práticas.

**Comment by cyz** [comment]
Obrigada por compartilhar - Participe da nossa série GitHub Foundations em Português em Outubro: https://aka.ms/brasil/githubfoundations
