### ISSUE TITLE
Experiência usando copilot

### ISSUE THREAD

**Issue by GreyPompom** [microsoft/Mastering-GitHub-Copilot-for-Paired-Programming#59]
Muito bom, ajuda muito com suporte de algumas duvidas simples, questoes complexas ele precisa de detalhamento mas é normal essa questao.

**Comment by cyz** [comment]
Obrigada por compartilhar - Participe da nossa série GitHub Foundations em Português em Outubro: https://aka.ms/brasil/githubfoundations
