### ISSUE TITLE
Feedback github copilot esquecido.

### ISSUE THREAD

**Issue by heberthreinstein** [microsoft/Mastering-GitHub-Copilot-for-Paired-Programming#61]
Uso copilot a mais de um ano, e me ajuda muito a acelerar meu processo, mas tem um ponto que acho que poderia melhor, que é ele se esquecer de algo que fiz a 2 min, por exemplo, crio uma entidade com alguns atributos, ao criar um service ele consegue se lembrar dos atributos que acabei de criar e insere sugestões com os nomes corretos, mas percebo que logo ele se esquece, acredito que se eu mude de modulo ou va abra outra classe bao relacionada ele perde a referencia da entidade que criei. No mais ele é incrivel e sugere muito bem as coisas, as vezes só preciso corrigir os nomes das coisas que ele começa inventar heheh.

**Comment by cyz** [comment]
Obrigada por compartilhar - Participe da nossa série GitHub Foundations em Português em Outubro: https://aka.ms/brasil/githubfoundations
