### ISSUE TITLE
Utilizando o Copilot

### ISSUE THREAD

**Issue by KarinaPadilha2512** [microsoft/Mastering-GitHub-Copilot-for-Paired-Programming#62]
Olá!!

A experiência tem sido incrível... economizando meu tempo e me dando boas ideias...o auto complete aumentou significativamente minha produtividade me permitindo focar em tarefas mais estratégicas.

**Comment by cyz** [comment]
Obrigada por compartilhar - Participe da nossa série GitHub Foundations em Português em Outubro: https://aka.ms/brasil/githubfoundations
