### ISSUE TITLE
Indo além do básico com o githubcopilot

### ISSUE THREAD

**Issue by arthurmgo** [microsoft/Mastering-GitHub-Copilot-for-Paired-Programming#63]
Na empresa em que trabalho, estamos testando o github copilot a muito tempo. Eu e outro arquiteto (Pedro Eustaquio) temos trabalhado criando complementos para a extensão do GITHUB COPILOT no vscode. Um dos nossos experimentos foi criar uma extensao para facilitar em tarefas do dia a dia, como revisão de código automatizada com prompts e codeguides do usuário. 
Além disso testamos várias outras features, no uso avançado dar contexto dos arquivos que você quer que o copilot foque é muito importante.

Eu amei essa capacidade do github copilot de permitir que criemos nossos próprios participantes de chat. Para problemas específicos ter essa capacidade de ampliar de forma fácil as funcionalidades do copilot é extremamente útil. Aguardo ansiosamente para que essa funcionalidade fique presente nas ides da jetbrains e no visual studio.

**Comment by cyz** [comment]
Obrigada por compartilhar - Participe da nossa série GitHub Foundations em Português em Outubro: https://aka.ms/brasil/githubfoundations
