### ISSUE TITLE
Minha experiência com GitHub copilot

### ISSUE THREAD

**Issue by dev-azevedo** [microsoft/Mastering-GitHub-Copilot-for-Paired-Programming#70]
Muito bom, ajuda com algumas duvidas simples, questoes complexas ele precisa de detalhamento mas é normal. Acredito que explorando melhor a ferramenta irei ter um resultado melhor.

**Comment by cyz** [comment]
Obrigada por compartilhar - Participe da nossa série GitHub Foundations em Português em Outubro: https://aka.ms/brasil/githubfoundations
