### ISSUE TITLE
Usando Github copilot

### ISSUE THREAD

**Issue by mathsou** [microsoft/Mastering-GitHub-Copilot-for-Paired-Programming#71]
Tenho usado o Github copilot a alguns dias, e facilita muito o processo de desenvolvimento, ajudando em tarefas repetitivas ou em alguma lógica que levaria mais tempo para criar manualmente. Além do chat onde posso tirar dúvidas de forma mais rápida do que levaria para encontrar.

**Comment by cyz** [comment]
Obrigada por compartilhar - Participe da nossa série GitHub Foundations em Português em Outubro: https://aka.ms/brasil/githubfoundations
