### ISSUE TITLE
Feedback usando github copilot para análise de código legado

### ISSUE THREAD

**Issue by pedropefj** [microsoft/Mastering-GitHub-Copilot-for-Paired-Programming#72]
Usando github copilot para entender legados

Na empresa em que trabalho recebi o desafio de encontra problemas no código de um legado (gigante) de um possível cliente, onde eu tinha que fazer uma proposta de possíveis melhorias.

Usei o @workspace do copilot para analisar o projeto e e me retornar os problemas e me dá possíveis soluções,  economizou bastante tempo na análise e os resultados foram bem satisfatórios.

**Comment by cyz** [comment]
Obrigada por compartilhar - Participe da nossa série GitHub Foundations em Português em Outubro: https://aka.ms/brasil/githubfoundations
