### ISSUE TITLE
Minha experiência com copilot

### ISSUE THREAD

**Issue by LaisaGarlini** [microsoft/Mastering-GitHub-Copilot-for-Paired-Programming#74]
Minha experiência tem sido muito massa, ajuda com as sugestões de código e com isso acelera o processo, facilitando também em muitos momentos. Evita também cometer erros comuns, sabendo usar, é topp!

**Comment by cyz** [comment]
Obrigada por compartilhar - Participe da nossa série GitHub Foundations em Português em Outubro: https://aka.ms/brasil/githubfoundations
