### ISSUE TITLE
Autocode

### ISSUE THREAD

**Issue by priscillatrevizan** [microsoft/Mastering-GitHub-Copilot-for-Paired-Programming#75]
O uso do copilot é muito prático e auxiliar muito meu dia a dia. Uma única questão que seria uma boa melhora é um questionamento na tela tipo "quer que eu te ajude" quando vc abre uma nova linha pra codar, pois as vezes, dou linha para pensar em uma solução, enquanto olho o código, e a sugestão automática do copilot joga meu código lá pra baixo... atrapalha um pouco o fluxo de pensamento.

**Comment by cyz** [comment]
Obrigada por compartilhar - Participe da nossa série GitHub Foundations em Português em Outubro: https://aka.ms/brasil/githubfoundations
