### ISSUE TITLE
Feedback GitHub Copilot

### ISSUE THREAD

**Issue by kevinuehara** [microsoft/Mastering-GitHub-Copilot-for-Paired-Programming#76]
Tive minha primeira experiência utilizando o GitHub Copilot após me tornar MVP e ter acesso ao Copilot. E após algum tempo utilizando, senti que minha produtividade aumentou mais.
Entender alguns erros e sugestões de melhorias no código são formas que eu mais utilizo para o desenvolvimento.

**Comment by cyz** [comment]
Obrigada por compartilhar - Participe da nossa série GitHub Foundations em Português em Outubro: https://aka.ms/brasil/githubfoundations
