### ISSUE TITLE
Experiência com Github Copilot

### ISSUE THREAD

**Issue by ademario** [microsoft/Mastering-GitHub-Copilot-for-Paired-Programming#82]
Tem em ajudado em tarefas repetitivas e sugestão de lógica mais simples.  Com temas mais complexos, ajuda com as ideias mas vejo ele ainda "se perder" ao aprofundar mais o tema.

**Comment by cyz** [comment]
Obrigada por compartilhar - Participe da nossa série GitHub Foundations em Português em Outubro: https://aka.ms/brasil/githubfoundations
