### ISSUE TITLE
Experiência com GitHub Copilot

### ISSUE THREAD

**Issue by AndrielPrado** [microsoft/Mastering-GitHub-Copilot-for-Paired-Programming#83]
Vejo que a utilização de tal recurso nos facilita com processos "repetitivos e básicos" além de nos fornecer sugestões de como elaborar tais linhas de código onde pode ficar mais consistente da forma que havíamos pensado  inicialmente.

Isso aumenta nosso aprendizado e nos faz sempre buscar criar algo melhor 😁😎

**Comment by cyz** [comment]
Obrigada por compartilhar - Participe da nossa série GitHub Foundations em Português em Outubro: https://aka.ms/brasil/githubfoundations
