### ISSUE TITLE
Minha experiência com copilot

### ISSUE THREAD

**Issue by viniciusdalastra** [microsoft/Mastering-GitHub-Copilot-for-Paired-Programming#84]
Fiz recentemente alguns testes com minha equipe com 3 desenvolvedores aumentamos muito a velocidade de desenvolvimento e também reduzimos a quantidade de problemas e retornos por revisão, assim aumentando muito a produtividade.

**Comment by cyz** [comment]
Obrigada por compartilhar - Participe da nossa série GitHub Foundations em Português em Outubro: https://aka.ms/brasil/githubfoundations
