### ISSUE TITLE
Uso do Github copilot com Java e Mssql

### ISSUE THREAD

**Issue by AndreLuisOvidio** [microsoft/Mastering-GitHub-Copilot-for-Paired-Programming#86]
No meu dia a dia eu desenvolvo soluções usando Java e banco de dados Mssql.

Usando o copilot eu gostei muito da função de autocomplete dele, me ajudou a otimizar e escrever código mais rápido.
Gostei bastante da função de explicação dele, em código legado Java, e em funções enormes de banco de dados ele conseguir entender e explicar em linguagem humana é uma função muito útil.

Uma dificuldade que eu vi é sobre autocomplete especificamente com sqls e funções de banco, como ele não tem contexto do meu banco ele normalmente autocompleta com algum campo ou tabela que não existe, talvez uma solução seria a possibilidade de integrar no VsCode para eu poder previamente adicionar as tabelas que eu quero usar no contexto atual.

Não foi pelo motivo acima, mas parei de usar o copilot a uns 3 meses por conta de achar solução que atendem bem a minha necessidade que não são pagas.

**Comment by cyz** [comment]
Obrigada por compartilhar - Participe da nossa série GitHub Foundations em Português em Outubro: https://aka.ms/brasil/githubfoundations
