### ISSUE TITLE
Experiência testando o Copilot

### ISSUE THREAD

**Issue by FsKummer** [microsoft/Mastering-GitHub-Copilot-for-Paired-Programming#88]
Eu uso o Copilot no meu dia a dia já a algum tempo e adoro. Claro que muitas vezes suas sugestões não chegam a aplicar, porém sempre agiliza o meu debugging e optomiza meu tempo para escrever testes automatizados e documentação.

**Comment by cyz** [comment]
Obrigada por compartilhar - Participe da nossa série GitHub Foundations em Português em Outubro: https://aka.ms/brasil/githubfoundations
