### ISSUE TITLE
Minha experiência com o Github Copilot

### ISSUE THREAD

**Issue by yujiyc** [microsoft/Mastering-GitHub-Copilot-for-Paired-Programming#90]
Como estudante de Ciência da Computação, tenho utilizado o Github Copilot em meus projetos da faculdade e do estágio para auxiliar meu aprendizado e desenvolvimento em programação. O Github Copilot tem me ajudado bastante, oferecendo sugestões e exemplos de código que facilitam o entendimento e otimizam meu tempo de desenvolvimento.

**Comment by cyz** [comment]
Obrigada por compartilhar - Participe da nossa série GitHub Foundations em Português em Outubro: https://aka.ms/brasil/githubfoundations
