### ISSUE TITLE
minha experiência com copilot

### ISSUE THREAD

**Issue by JoaoVitorGir** [microsoft/Mastering-GitHub-Copilot-for-Paired-Programming#91]
Minha experiência com o github copilot tem sido exelente, pois tem me ajudado com a codificação de varias etapas do meu código, dura te o desenvolvimento não preciso ficar perdendo com digitação de código, varias vezes ele me ajuda com o auto preenchimento que eu sinceramente acho mágico kkkk.

**Comment by cyz** [comment]
Obrigada por compartilhar - Participe da nossa série GitHub Foundations em Português em Outubro: https://aka.ms/brasil/githubfoundations
