### ISSUE TITLE
feedback utilizando copilot

### ISSUE THREAD

**Issue by DevJon94** [microsoft/Mastering-GitHub-Copilot-for-Paired-Programming#94]
Comecei a utilizar o copilot este ano, uso como um assistente no trabalho, lembrar um comando, pra pesquisas rapidas e ja houve uma vez um caso de manutenção num front de outro projeto de uma tecnologia e arquitetura que eu não conhecia. O copilot me ajudou a achar o ultimo erro que eu não estava enxergando na hora. Em resumo, é um copilot muito util, ajuda na produtividade e também pode ajudar nos estudos.

**Comment by cyz** [comment]
Obrigada por compartilhar - Participe da nossa série GitHub Foundations em Português em Outubro: https://aka.ms/brasil/githubfoundations
