### ISSUE TITLE
Experiência com o Copilot do GitHub 

### ISSUE THREAD

**Issue by TaisonPedrini** [microsoft/Mastering-GitHub-Copilot-for-Paired-Programming#95]
Já utilizei ele algumas vezes e ele me ajudou a desenvolver partes do código que eu não sabia como fazer. No geral ele me ajudou a conseguir construir meu código de modo mais eficiente.

**Comment by cyz** [comment]
Obrigada por compartilhar - Participe da nossa série GitHub Foundations em Português em Outubro: https://aka.ms/brasil/githubfoundations
