### ISSUE TITLE
Feedback de uso Copilot

### ISSUE THREAD

**Issue by matheuszap** [microsoft/Mastering-GitHub-Copilot-for-Paired-Programming#96]
Utilizo Copilot diariamente há cerca de um ano, tanto para fins profissionais quanto pessoais (projetos, faculdade, etc). 
A ferramenta torna muito mais fácil a realização de tarefas repetitivas, além de ser ótima para pair programming, oferecendo sugestões que muitas vezes não passam pela cabeça do desenvolvedor. Desta forma, permite a concentração em tarefas mais criativas e estratégicas, enquanto ele cuida das partes mais repetitivas.

**Comment by cyz** [comment]
Obrigada por compartilhar - Participe da nossa série GitHub Foundations em Português em Outubro: https://aka.ms/brasil/githubfoundations
