### ISSUE TITLE
Copilot é o MELHOR, não vivo mais sem 😍😍

### ISSUE THREAD

**Issue by nurycaroline** [microsoft/Mastering-GitHub-Copilot-for-Paired-Programming#97]
Invisto com prazer, a minha produtividade subiu muito. Copilot consegue entender muito bem sobre as regras que preciso escrever, raramente preciso fazer algum ajuste. Como adoro fazer projetos paralelos para aprender ou testar alguma tech, me ajuda muito a aprender novas abordagens e como melhorar meu codigo. 
Usei o plugin de explicação de código para ensinar novas pessoas na area da programação, e para ter uma visão diferente de pq a implementação foi feita de uma certa maneira.

**Comment by cyz** [comment]
Obrigada por compartilhar - Participe da nossa série GitHub Foundations em Português em Outubro: https://aka.ms/brasil/githubfoundations
