### ISSUE TITLE
Experiência com Copilot

### ISSUE THREAD

**Issue by Alison4kk** [microsoft/Mastering-GitHub-Copilot-for-Paired-Programming#99]
Minha experiência com o Copilot tem sido ótima, utilizo no trabalho constantemente para agilizar a escrita. No final funciona mais como um auto complete do que um tira dúvidas. Excelente ferramenta!

**Comment by cyz** [comment]
Obrigada por compartilhar - Participe da nossa série GitHub Foundations em Português em Outubro: https://aka.ms/brasil/githubfoundations
